name: json2dart
description: An absolute bare-bones web app.
version: 2.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.8.1"

dependencies:
  test: "^1.0.0"
  code_builder: "^3.1.1"
  recase: "^1.0.0+1"
  tuple: "^1.0.1"

dev_dependencies:
  build_runner: ^2.4.15
  build_test: ^2.2.3
  build_web_compilers: ^4.1.5
  lints: ^6.0.0
